<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Anu-pc" name="com.epoccoverter.testcases.TC01_Getrequest" tests="7" failures="0" timestamp="2023-04-09T03:55:57 IST" time="4.384" errors="1">
  <testcase name="testcase4_get" time="0.259" classname="com.epoccoverter.testcases.TC01_Getrequest"/>
  <system-out/>
  <testcase name="testcase5_get" time="0.240" classname="com.epoccoverter.testcases.TC01_Getrequest"/>
  <system-out/>
  <testcase name="testcase6_get" time="1.267" classname="com.epoccoverter.testcases.TC01_Getrequest"/>
  <system-out/>
  <testcase name="testcase3_get" time="0.322" classname="com.epoccoverter.testcases.TC01_Getrequest"/>
  <system-out/>
  <testcase name="testcase1_get" time="1.696" classname="com.epoccoverter.testcases.TC01_Getrequest"/>
  <system-out/>
  <testcase name="testcase7_get" time="0.236" classname="com.epoccoverter.testcases.TC01_Getrequest">
    <error type="java.time.format.DateTimeParseException" message="Text &#039;318857-05-20 21:46:39 GMT+04:00&#039; could not be parsed at index 0">
      <![CDATA[java.time.format.DateTimeParseException: Text '318857-05-20 21:46:39 GMT+04:00' could not be parsed at index 0
at java.time.format.DateTimeFormatter.parseResolved0(Unknown Source)
at java.time.format.DateTimeFormatter.parse(Unknown Source)
at java.time.LocalDate.parse(Unknown Source)
at com.epocconverter.responsevalidation.Responsevalidation.datevalidation(Responsevalidation.java:40)
at com.epoccoverter.testcases.TC01_Getrequest.testcase7_get(TC01_Getrequest.java:252)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testcase7_get -->
  <system-out/>
  <testcase name="testcase2_invalidtimestamp" time="0.364" classname="com.epoccoverter.testcases.TC01_Getrequest"/>
  <system-out/>
</testsuite> <!-- com.epoccoverter.testcases.TC01_Getrequest -->
